"""
Observability module for NAICS MCP Server.
"""

from .audit import SearchAuditLog, SearchEvent
from .logging import (
    JSONFormatter,
    LogConfig,
    StructuredLogger,
    TextFormatter,
    clear_request_context,
    generate_correlation_id,
    generate_request_id,
    get_logger,
    get_request_context,
    log_operation,
    log_server_ready,
    log_server_shutdown,
    log_server_start,
    log_tool_call,
    sanitize_dict,
    sanitize_text,
    set_request_context,
    set_service_metadata,
    setup_logging,
    setup_logging_from_config,
)
from .metrics import (
    Timer,
    get_metrics,
    get_metrics_text,
    initialize_metrics,
    record_cache_hit,
    record_cache_miss,
    record_crossref_lookup,
    record_db_connection_error,
    record_embedding_batch,
    record_rate_limit_check,
    record_search_fallback,
    record_search_metrics,
    reset_metrics,
    track_db_query,
    track_embedding_operation,
    track_tool_metrics,
    update_cache_stats,
    update_data_stats,
    update_db_connections,
    update_health_status,
    update_rate_limit_stats,
)
from .rate_limiting import (
    RateLimiter,
    RateLimitResult,
    TokenBucket,
    ToolCategory,
    rate_limited,
    search_rate_limited,
    classify_rate_limited,
    batch_rate_limited,
    hierarchy_rate_limited,
    analytics_rate_limited,
    health_rate_limited,
    workbook_rate_limited,
)

__all__ = [
    # Audit
    "SearchAuditLog",
    "SearchEvent",
    # Logging
    "setup_logging",
    "setup_logging_from_config",
    "get_logger",
    "set_request_context",
    "clear_request_context",
    "get_request_context",
    "generate_request_id",
    "generate_correlation_id",
    "set_service_metadata",
    "sanitize_text",
    "sanitize_dict",
    "log_tool_call",
    "log_operation",
    "log_server_start",
    "log_server_ready",
    "log_server_shutdown",
    "LogConfig",
    "JSONFormatter",
    "TextFormatter",
    "StructuredLogger",
    # Metrics
    "initialize_metrics",
    "reset_metrics",
    "get_metrics",
    "get_metrics_text",
    "Timer",
    "track_tool_metrics",
    "track_db_query",
    "track_embedding_operation",
    "record_search_metrics",
    "record_cache_hit",
    "record_cache_miss",
    "update_cache_stats",
    "record_search_fallback",
    "record_crossref_lookup",
    "update_health_status",
    "update_data_stats",
    "record_db_connection_error",
    "update_db_connections",
    "record_embedding_batch",
    "record_rate_limit_check",
    "update_rate_limit_stats",
    # Rate Limiting
    "RateLimiter",
    "RateLimitResult",
    "TokenBucket",
    "ToolCategory",
    "rate_limited",
    "search_rate_limited",
    "classify_rate_limited",
    "batch_rate_limited",
    "hierarchy_rate_limited",
    "analytics_rate_limited",
    "health_rate_limited",
    "workbook_rate_limited",
]
