"""
Observability module for NAICS MCP Server.
"""

from .audit import SearchAuditLog, SearchEvent
from .logging import (
    LogConfig,
    clear_request_context,
    generate_request_id,
    get_logger,
    log_operation,
    log_server_ready,
    log_server_shutdown,
    log_server_start,
    log_tool_call,
    sanitize_dict,
    sanitize_text,
    set_request_context,
    setup_logging,
)
from .metrics import (
    Timer,
    get_metrics,
    get_metrics_text,
    initialize_metrics,
    record_cache_hit,
    record_cache_miss,
    record_crossref_lookup,
    record_db_connection_error,
    record_embedding_batch,
    record_search_fallback,
    record_search_metrics,
    reset_metrics,
    track_db_query,
    track_embedding_operation,
    track_tool_metrics,
    update_cache_stats,
    update_data_stats,
    update_db_connections,
    update_health_status,
)

__all__ = [
    # Audit
    "SearchAuditLog",
    "SearchEvent",
    # Logging
    "setup_logging",
    "get_logger",
    "set_request_context",
    "clear_request_context",
    "generate_request_id",
    "sanitize_text",
    "sanitize_dict",
    "log_tool_call",
    "log_operation",
    "log_server_start",
    "log_server_ready",
    "log_server_shutdown",
    "LogConfig",
    # Metrics
    "initialize_metrics",
    "reset_metrics",
    "get_metrics",
    "get_metrics_text",
    "Timer",
    "track_tool_metrics",
    "track_db_query",
    "track_embedding_operation",
    "record_search_metrics",
    "record_cache_hit",
    "record_cache_miss",
    "update_cache_stats",
    "record_search_fallback",
    "record_crossref_lookup",
    "update_health_status",
    "update_data_stats",
    "record_db_connection_error",
    "update_db_connections",
    "record_embedding_batch",
]
